export const CATEGORIES = [
	{ id: "news", label: "뉴스", emoji: "📰" },
	{ id: "tech", label: "기술", emoji: "💻" },
	{ id: "fashion", label: "패션", emoji: "👗" },
	{ id: "finance", label: "금융", emoji: "📈" },
	{ id: "health", label: "건강", emoji: "💪" },
	{ id: "food", label: "음식", emoji: "🍔" },
	{ id: "entertainment", label: "엔터테인먼트", emoji: "🎬" },
	{ id: "sports", label: "스포츠", emoji: "⚽" },
];

export const WIDGET_LIST = [
	{ id: "health", label: "건강 (Google Fit)", category: "core" },
	{ id: "calendar", label: "캘린더 (Google)", category: "core" },
	{ id: "todo", label: "오늘의 할 일", category: "core" },
	{ id: "briefing", label: "AI 브리핑", category: "core" },
	{ id: "trends", label: "실시간 트렌드", category: "core" },
	{ id: "stocks", label: "주식/환율", category: "core" },
	{ id: "weather", label: "날씨", category: "core" },
	{ id: "foodRoulette", label: "메뉴 결정 도우미", category: "smart" },
	{ id: "brandDrop", label: "브랜드 Drop D-Day", category: "smart" },
	{ id: "restaurants", label: "주변 맛집", category: "smart" },
];

export const DEFAULT_VIS = {
	todo: true,
	health: true,
	briefing: true,
	trends: true,
	foodRoulette: true,
	stocks: true,
	weather: true,
	brandDrop: true,
	calendar: true,
	restaurants: false,
};

export const DEFAULT_LAYOUTS = {
	lg: [
		{ i: "health", x: 0, y: 0, w: 3, h: 10, minW: 2, minH: 6 },
		{ i: "calendar", x: 0, y: 10, w: 3, h: 8, minW: 2, minH: 5 },
		{ i: "todo", x: 0, y: 18, w: 3, h: 8, minW: 2, minH: 5 },
		{ i: "briefing", x: 3, y: 0, w: 3, h: 9, minW: 2, minH: 6 },
		{ i: "trends", x: 3, y: 9, w: 3, h: 5, minW: 2, minH: 3 },
		{ i: "foodRoulette", x: 3, y: 14, w: 3, h: 7, minW: 2, minH: 4 },
		{ i: "stocks", x: 6, y: 0, w: 3, h: 9, minW: 2, minH: 5 },
		{ i: "weather", x: 6, y: 9, w: 3, h: 5, minW: 2, minH: 3 },
		{ i: "brandDrop", x: 6, y: 14, w: 3, h: 9, minW: 2, minH: 5 },
		{ i: "restaurants", x: 6, y: 23, w: 3, h: 8, minW: 2, minH: 5 },
		{ i: "smart_카메라", x: 9, y: 0, w: 3, h: 12, minW: 2, minH: 6 },
		{ i: "smart_노트북", x: 9, y: 12, w: 3, h: 12, minW: 2, minH: 6 },
		{ i: "addSmart", x: 9, y: 24, w: 3, h: 2, minW: 2, minH: 2, static: true },
	],
	md: [
		{ i: "health", x: 0, y: 0, w: 5, h: 10, minW: 3, minH: 6 },
		{ i: "calendar", x: 0, y: 10, w: 5, h: 8, minW: 3, minH: 5 },
		{ i: "todo", x: 0, y: 18, w: 5, h: 8, minW: 3, minH: 5 },
		{ i: "briefing", x: 5, y: 0, w: 5, h: 9, minW: 3, minH: 6 },
		{ i: "trends", x: 5, y: 9, w: 5, h: 5, minW: 3, minH: 3 },
		{ i: "stocks", x: 5, y: 14, w: 5, h: 9, minW: 3, minH: 5 },
		{ i: "weather", x: 0, y: 26, w: 5, h: 5, minW: 3, minH: 3 },
		{ i: "foodRoulette", x: 5, y: 23, w: 5, h: 7, minW: 3, minH: 4 },
		{ i: "brandDrop", x: 0, y: 31, w: 5, h: 9, minW: 3, minH: 5 },
		{ i: "restaurants", x: 5, y: 30, w: 5, h: 8, minW: 3, minH: 5 },
		{ i: "smart_카메라", x: 0, y: 40, w: 5, h: 12, minW: 3, minH: 6 },
		{ i: "smart_노트북", x: 5, y: 40, w: 5, h: 12, minW: 3, minH: 6 },
		{ i: "addSmart", x: 0, y: 52, w: 10, h: 2, minW: 3, minH: 2, static: true },
	],
	sm: [
		{ i: "health", x: 0, y: 0, w: 6, h: 10, minW: 4, minH: 6 },
		{ i: "calendar", x: 0, y: 10, w: 6, h: 8, minW: 4, minH: 5 },
		{ i: "briefing", x: 0, y: 18, w: 6, h: 9, minW: 4, minH: 6 },
		{ i: "todo", x: 0, y: 27, w: 6, h: 8, minW: 4, minH: 5 },
		{ i: "trends", x: 0, y: 35, w: 6, h: 5, minW: 4, minH: 3 },
		{ i: "stocks", x: 0, y: 40, w: 6, h: 9, minW: 4, minH: 5 },
		{ i: "weather", x: 0, y: 49, w: 6, h: 5, minW: 4, minH: 3 },
		{ i: "foodRoulette", x: 0, y: 54, w: 6, h: 7, minW: 4, minH: 4 },
		{ i: "brandDrop", x: 0, y: 61, w: 6, h: 9, minW: 4, minH: 5 },
		{ i: "restaurants", x: 0, y: 70, w: 6, h: 8, minW: 4, minH: 5 },
		{ i: "smart_카메라", x: 0, y: 78, w: 6, h: 12, minW: 4, minH: 6 },
		{ i: "smart_노트북", x: 0, y: 90, w: 6, h: 12, minW: 4, minH: 6 },
		{ i: "addSmart", x: 0, y: 102, w: 6, h: 2, minW: 4, minH: 2, static: true },
	],
};
